# Generated by Django 6.0.3 on 2026-03-20 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('montant_unitaire', models.DecimalField(decimal_places=0, max_digits=10)),
                ('nombre_participants', models.IntegerField()),
                ('numero_receveur', models.CharField(max_length=20)),
                ('operateur_receveur', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete'), ('expiree', 'Expiree'), ('suspendue', 'Suspendue'), ('annulee', 'Annulee')], default='active', max_length=20)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('est_recurrente', models.BooleanField(default=False)),
                ('periodicite', models.CharField(blank=True, max_length=20)),
                ('date_expiration', models.DateTimeField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('participants_payes', models.IntegerField(default=0)),
                ('montant_collecte', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('pdf_participants_url', models.URLField(blank=True)),
                ('carte_celebration_url', models.URLField(blank=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cotisations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Paye'), ('echoue', 'Echoue'), ('rembourse', 'Rembourse')], default='en_attente', max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_avec_frais', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('frais_kotizo', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('paydunya_token', models.CharField(blank=True, max_length=200)),
                ('date_participation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('recu_confirme', models.BooleanField(default=False)),
                ('date_confirmation_recu', models.DateTimeField(blank=True, null=True)),
                ('recu_pdf_url', models.URLField(blank=True)),
                ('recu_image_url', models.URLField(blank=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='cotisations.cotisation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participations',
                'unique_together': {('cotisation', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('arnaque', 'Arnaque'), ('contenu_inapproprie', 'Contenu inapproprie'), ('spam', 'Spam'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('examine', 'Examine'), ('confirme', 'Confirme'), ('rejete', 'Rejete')], default='en_attente', max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='cotisations.cotisation')),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signalements',
                'unique_together': {('cotisation', 'signaleur')},
            },
        ),
    ]
