# Generated by Django 6.0.3 on 2026-03-20 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('numero_actuel', models.CharField(blank=True, max_length=20)),
                ('dernier_ping', models.DateTimeField(blank=True, null=True)),
                ('nb_pings_echoues', models.IntegerField(default=0)),
                ('date_derniere_panne', models.DateTimeField(blank=True, null=True)),
                ('date_retablissement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statut_whatsapp',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('paiement_recu', 'Paiement recu'), ('cotisation_complete', 'Cotisation complete'), ('cotisation_expiree', 'Cotisation expiree'), ('quickpay_expire', 'Quick Pay expire'), ('verification_approuvee', 'Verification approuvee'), ('verification_rejetee', 'Verification rejetee'), ('sanction', 'Sanction'), ('remboursement', 'Remboursement'), ('rappel', 'Rappel'), ('ambassadeur', 'Ambassadeur'), ('whatsapp_panne', 'WhatsApp panne'), ('whatsapp_retabli', 'WhatsApp retabli'), ('promo_verification', 'Promo verification'), ('systeme', 'Systeme')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
