# Generated by Django 6.0.3 on 2026-03-20 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_avec_frais', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('frais_kotizo', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('numero_receveur', models.CharField(max_length=20)),
                ('operateur_receveur', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('paye', 'Paye'), ('expire', 'Expire'), ('annule', 'Annule')], default='actif', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('paydunya_token', models.CharField(blank=True, max_length=200)),
                ('recu_pdf_url', models.URLField(blank=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickpays_crees', to=settings.AUTH_USER_MODEL)),
                ('payeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickpays_payes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quickpay',
                'ordering': ['-date_creation'],
            },
        ),
    ]
