# Generated by Django 6.0.3 on 2026-03-20 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200, unique=True)),
                ('raison', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blacklist_devices',
            },
        ),
        migrations.CreateModel(
            name='BlacklistNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('raison', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blacklist_numeros',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('pseudo', models.CharField(max_length=20, unique=True)),
                ('nom_verifie', models.BooleanField(default=False)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('pays', models.CharField(choices=[('TG', 'Togo'), ('BJ', 'Benin'), ('CI', "Cote d'Ivoire"), ('SN', 'Senegal'), ('GH', 'Ghana'), ('ML', 'Mali'), ('BF', 'Burkina Faso')], default='TG', max_length=5)),
                ('niveau', models.CharField(choices=[('basique', 'Basique'), ('verifie', 'Verifie'), ('business', 'Business')], default='basique', max_length=20)),
                ('photo', models.URLField(blank=True)),
                ('ville_approx', models.CharField(blank=True, max_length=100)),
                ('consentement_position', models.BooleanField(default=False)),
                ('email_verifie', models.BooleanField(default=False)),
                ('token_verification_email', models.CharField(blank=True, max_length=100)),
                ('token_email_expires', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('whatsapp_verifie', models.BooleanField(default=False)),
                ('whatsapp_verify_token', models.CharField(blank=True, max_length=20)),
                ('whatsapp_token_expires', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_nouveau_numero_pending', models.CharField(blank=True, max_length=20)),
                ('cgu_acceptees', models.BooleanField(default=False)),
                ('cgu_version', models.CharField(blank=True, max_length=10)),
                ('cgu_date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('cgu_ip_acceptation', models.GenericIPAddressField(blank=True, null=True)),
                ('cotisations_creees_aujourd_hui', models.IntegerField(default=0)),
                ('cotisations_creees_fenetre', models.IntegerField(default=0)),
                ('debut_fenetre_7j', models.DateTimeField(blank=True, null=True)),
                ('date_reset_compteur', models.DateField(blank=True, null=True)),
                ('nb_parrainages_actifs', models.IntegerField(default=0)),
                ('code_parrainage', models.CharField(blank=True, max_length=10, unique=True)),
                ('prix_verification', models.IntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('admin_role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('moderateur', 'Moderateur'), ('support', 'Support'), ('finance', 'Finance'), ('verification', 'Verification'), ('lecteur', 'Lecteur')], max_length=20, null=True)),
                ('admin_permissions', models.JSONField(blank=True, default=list)),
                ('admin_whatsapp_numero', models.CharField(blank=True, max_length=20)),
                ('admin_whatsapp_pin', models.CharField(blank=True, max_length=128)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion_app', models.DateTimeField(blank=True, null=True)),
                ('fcm_token', models.TextField(blank=True)),
                ('device_id', models.CharField(blank=True, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AlerteFraude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('multi_comptes', 'Multi comptes'), ('signalements_multiples', 'Signalements multiples'), ('creation_rapide', 'Creation rapide'), ('numero_suspect', 'Numero suspect'), ('ip_suspecte', 'IP suspecte'), ('fraude_paydunya', 'Fraude PayDunya'), ('injection_ia', 'Injection IA')], max_length=30)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('resolue', 'Resolue'), ('faux_positif', 'Faux positif')], default='nouvelle', max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_fraude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alertes_fraude',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeBusinessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('type_activite', models.CharField(choices=[('association', 'Association'), ('entreprise', 'Entreprise'), ('ong', 'ONG'), ('cooperative', 'Cooperative'), ('autre', 'Autre')], max_length=20)),
                ('volume_mensuel_estime', models.IntegerField(default=0)),
                ('raison_demande', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuve'), ('rejete', 'Rejete'), ('expire', 'Expire')], default='en_attente', max_length=20)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_expiration_gratuite', models.DateTimeField(blank=True, null=True)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('note_admin', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'demandes_business',
            },
        ),
        migrations.CreateModel(
            name='PromoVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField(default=500)),
                ('active', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('nb_utilisations', models.IntegerField(default=0)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promos_verification',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField(choices=[(0, 'Avertissement'), (1, 'Restriction legere'), (2, 'Restriction moyenne'), (3, 'Degradation compte'), (4, 'Fermeture temporaire'), (5, 'Bannissement permanent')])),
                ('raison', models.TextField()),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('contestee', models.BooleanField(default=False)),
                ('note_contestation', models.TextField(blank=True)),
                ('appliquee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_appliquees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sanctions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='VerificationIdentite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('cni', 'CNI'), ('passeport', 'Passeport'), ('consulaire', 'Carte consulaire')], max_length=20)),
                ('photo_recto', models.URLField()),
                ('photo_verso', models.URLField()),
                ('liveness_valide', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuve'), ('rejete', 'Rejete')], default='en_attente', max_length=20)),
                ('note_admin', models.TextField(blank=True)),
                ('prix_applique', models.IntegerField(default=1000)),
                ('raison_prix_reduit', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verifications_identite',
            },
        ),
    ]
