# Generated by Django 6.0.3 on 2026-03-20 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('payin', 'PayIn'), ('payout', 'PayOut'), ('frais_verification', 'Frais verification'), ('frais_business', 'Frais business')], max_length=30)),
                ('source', models.CharField(choices=[('cotisation', 'Cotisation'), ('quickpay', 'Quick Pay'), ('verification', 'Verification'), ('business', 'Business')], max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('frais_kotizo', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('frais_paydunya', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('montant_net', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('initie', 'Initie'), ('en_attente', 'En attente'), ('complete', 'Complete'), ('echoue', 'Echoue'), ('rembourse', 'Rembourse')], default='initie', max_length=20)),
                ('paydunya_token', models.CharField(blank=True, max_length=200)),
                ('telephone_receveur', models.CharField(blank=True, max_length=20)),
                ('operateur', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('webhook_recu', models.BooleanField(default=False)),
                ('webhook_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(choices=[('erreur_technique', 'Erreur technique'), ('double_paiement', 'Double paiement'), ('fraude_confirmee', 'Fraude confirmee'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField()),
                ('preuves_urls', models.JSONField(default=list)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepte'), ('rejete', 'Rejete'), ('rembourse', 'Rembourse')], default='en_attente', max_length=20)),
                ('note_admin', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paiements.transaction')),
            ],
            options={
                'db_table': 'demandes_remboursement',
            },
        ),
    ]
