# Generated by Django 6.0.3 on 2026-03-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('nb_nouveaux_users', models.IntegerField(default=0)),
                ('nb_transactions', models.IntegerField(default=0)),
                ('volume_total', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('revenus_kotizo', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('nb_cotisations_creees', models.IntegerField(default=0)),
                ('nb_quickpay', models.IntegerField(default=0)),
                ('nb_alertes_fraude', models.IntegerField(default=0)),
                ('nb_tickets_ouverts', models.IntegerField(default=0)),
                ('nb_verifications_soumises', models.IntegerField(default=0)),
                ('nb_promos_utilisees', models.IntegerField(default=0)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rapports_journaliers',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('etat', models.CharField(max_length=100)),
                ('plateforme', models.CharField(blank=True, max_length=10)),
                ('version_app', models.CharField(blank=True, max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'state_logs',
                'ordering': ['-date_creation'],
            },
        ),
    ]
